on:
  push:

jobs:
  build:
    runs-on: windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run:  bash ${GITHUB_WORKSPACE}/strings/1.sh    
