name: Python Build

on:
  push:

jobs:
  build:
    runs-on: windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        run: |
          echo " running all the pyhton files.."
          for file in strings/*.py
          do
           echo " Executing: $file"
           python "$file"
          done
          
