name: Python Build

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Shell Script
        shell: bash
        run: |
          chmod +x strings/1.sh
          ./strings/1.sh
